// Copyright (c) 2010 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Boilerplate code was generated by http://burtonini.com/cgi/gobject.py

#ifndef CHROME_BROWSER_AUTOCOMPLETE_UNDO_ENTRY_H_
#define CHROME_BROWSER_AUTOCOMPLETE_UNDO_ENTRY_H_

#include <gtk/gtk.h>
#include "undo_manager.h"

G_BEGIN_DECLS

#define GTK_TYPE_UNDO_ENTRY gtk_undo_entry_get_type()

#define GTK_UNDO_ENTRY(obj) \
  (G_TYPE_CHECK_INSTANCE_CAST((obj), GTK_TYPE_UNDO_ENTRY, GtkUndoEntry))

#define GTK_UNDO_ENTRY_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_CAST((klass), GTK_TYPE_UNDO_ENTRY, GtkUndoEntryClass))

#define GTK_IS_UNDO_ENTRY(obj) \
  (G_TYPE_CHECK_INSTANCE_TYPE((obj), GTK_TYPE_UNDO_ENTRY))

#define GTK_IS_UNDO_ENTRY_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_TYPE((klass), GTK_TYPE_UNDO_ENTRY))

#define GTK_UNDO_ENTRY_GET_CLASS(obj) \
  (G_TYPE_INSTANCE_GET_CLASS((obj), GTK_TYPE_UNDO_ENTRY, GtkUndoEntryClass))

typedef struct
{
	GtkEntry parent;
	GtkEntryUndoManager *undo_manager_;
} GtkUndoEntry;

typedef struct
{
	GtkEntryClass parent_class;

	void ( *undo ) ( GtkUndoEntry * );
	void ( *redo ) ( GtkUndoEntry * );
} GtkUndoEntryClass;

GType gtk_undo_entry_get_type ( void );

GtkWidget* gtk_undo_entry_new ( GtkEntryBuffer *buffer );

G_END_DECLS

#endif  // CHROME_BROWSER_AUTOCOMPLETE_UNDO_ENTRY_H_

